# fly.toml app configuration file generated for reader555bot on 2024-10-07T17:32:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reader555bot'
primary_region = 'lhr'

[build]
  builder = 'heroku/buildpacks:20'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = 'tcp'
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
